### ISSUE TITLE
Implementar /friends last

### ISSUE THREAD

**Issue by vitor-sanc** [USPCodeLabSanca/approxima-chatbot-node#16]
Motivo: as pessoas não querem recuperar toda a lista de amigos quando conectam com uma pessoa nova, apenas a última. Logo, para evitar de criar um comando novo (e evitar poluir ainda mais a lista de comandos), basta implementar um argumento no /friends que dirá se o usuário quer recuperar todas as conexões (no caso deste ser vazio) ou apenas a última (caso contrário).

**Comment by Math-O5** [comment]
@vitor-san Assign eu, pvf!
